name: GitHub Actions Demo
on:
  workflow_dispatch:
jobs:
  print-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Pie"
      - name: Hello World 2
        run: echo "Pie 2"

