name: website-status-check

on:
  schedule:
    - cron: '0/5 * * * *'

jobs: 
     website-status-check:
     steps:
       powershell: |
         $url = "https://iac.jsf.mil"
          $expectedStatusCode = 403

         try {
            $response = Invoke-WebRequest -Uri $url -Method Get
            $statusCode = $response.StatusCode

            if ($statusCode -eq $expectedStatusCode) {
                Write-Output "Website is up and running. Status code: $statusCode"
            } else {
                Write-Error "Website returned an unexpected status code: $statusCode"
            }
         } catch {
            Write-Error "An error occurred while checking the website: $_.Exception.Message"
         }
       displayName: 'Check Website Status'
       continueOnError: true # Continue to next step even if there's an error
       condition: succeeded() # Only run this step if the previous step succeeded
