name: website-status-check

trigger:
  recurrence:
    frequency: Minute
    interval: 5

jobs:
  job: website-check-job
  steps:
    powershell: |
      $url = "https://iac.jsf.mil"
      $expectedStatusCode = 403

      try {
          $response = Invoke-WebRequest -Uri $url -Method Get
          $statusCode = $response.StatusCode

          if ($statusCode -eq $expectedStatusCode) {
              Write-Output "Website is up and running. Status code: $statusCode"
          } else {
              Write-Error "Website returned an unexpected status code: $statusCode"
          }
      } catch {
          Write-Error "An error occurred while checking the website: $_.Exception.Message"
      }
    displayName: 'Check Website Status'
    continueOnError: true # Continue to next step even if there's an error
    powershell: |
      # Your PowerShell script to dispatch the status code or take further actions goes here
      # Example: Send an email or trigger an alert

    displayName: 'Dispatch Status Code'
    condition: succeeded() # Only run this step if the previous step succeeded

