name: website-status-check

on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'

jobs: 
  website-status-check:
   name: Website Status Check
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Check Status
      shell: pwsh
      run: |
         $url = "https://iac.jsf.mil"
          $expectedStatusCode = 403

         try {
            $response = Invoke-WebRequest -Uri $url
            $statusCode = $response.StatusCode

            if ($statusCode -eq $expectedStatusCode) {
                Write-Output "Website is up and running. Status code: $statusCode"
            } else {
                Write-Error "Website returned an unexpected status code: $statusCode"
            }
         } catch {
            Write-Error "An error occurred while checking the website: $_.Exception.Message"
         }
