- name: Check Website Status
on:
  workflow_dispatch:
  script: |
    $url = "https://example.com"
    $expectedStatusCode = 200
    
    try {
        $response = Invoke-WebRequest -Uri $url -Method Get
        $statusCode = $response.StatusCode
        
        if ($statusCode -eq $expectedStatusCode) {
            Write-Output "Website is up and running. Status code: $statusCode"
        } else {
            Write-Error "Website returned an unexpected status code: $statusCode"
        }
    } catch {
        Write-Error "An error occurred while checking the website: $_.Exception.Message"
    }
